### ISSUE TITLE
nstore.new callback called twice

### ISSUE THREAD

**Issue by ricardobeat** [creationix/nstore#10]
using express+coffescript:

```
projects = store.new 'projects.db', ->
    app.listen 3000, 'localhost'
```

the callback is called twice. Is this a bug?

(a side-effect of that is that `projects` seems to refer to the wrong object, I can't call projects.all == undefined)

**Comment by creationix** [comment]
what's the generated js look like?

**Comment by ricardobeat** [comment]
```
var projects;
projects = store["new"]('projects.db', function() {
    return app.listen(3000, 'localhost');
});
```

I don't see anything wrong there. `store = require('nstore')` of course. I'll put the whole thing on a gist later this afternoon.

**Comment by creationix** [comment]
Is this still broken?

**Comment by oleksiyk** [comment]
HI!  This is still broken, the .new() callback is called twice when the .db file contains a single record. The problem is probably here:

nstore.j:

var scanned = false;

............

function check() {
        if (counter === 0 && scanned !== undefined) {
............

the 'scanned' variable should be checked against 'false' and not 'undefined'.

Thanks!
